### ISSUE TITLE
About Section Problems

### ISSUE THREAD

**Issue by asherkeely** [RoboBibb/robobibb.github.io#3]
The paragraphs on the about page are centered to the left. Maybe center them to make them more appealing. When we add photos, having some centered in different ways might look attractive, but right conformity would look best.

**Comment by asherkeely** [comment]
We should bullet point the accomplishments so the years are the title

**Comment by asherkeely** [comment]
It says "Berth at worlds...." 
?????????????

**Comment by dvtate** [comment]
@theresiajahja

**Comment by theresiajahja** [comment]
@asherkeely I thought it was centered to the middle...

**Comment by theresiajahja** [comment]
@asherkeely I only copied and pasted what you had on the google doc, I didn't make anything up.

**Comment by dvtate** [comment]
@theresiajahja I changed the main stylesheet so that things are centered to the left, this is why the text isn't centered anymore, I'd reccomend you change the page to accommodate this... You can still center things using the `w3-center` class and/or setting the CSS property `text-align: center;` to your local style-sheet or the DOM style property.
`<style> div.text-container { text-align: center !important; }</style>`
`<div style="text-align: center">this text will be centered</div>`

**Comment by dvtate** [comment]
Keely likes to pick on people don't take it personally :)
